<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<?mso-application progid="Excel.Sheet"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet" xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:x="urn:schemas-microsoft-com:office:excel" xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet" xmlns:html="http://www.w3.org/TR/REC-html40" xmlns:dt="uuid:C2F41010-65B3-11d1-A29F-00AA00C14882">
    <DocumentProperties xmlns="urn:schemas-microsoft-com:office:office"><Author>RR Donnelley</Author><LastAuthor>archforce</LastAuthor><LastPrinted>2021-08-30T02:23:00Z</LastPrinted><Created>2015-09-28T07:42:00Z</Created><LastSaved>2021-08-30T06:46:42Z</LastSaved><Company>RR Donnelley</Company></DocumentProperties>
    <CustomDocumentProperties xmlns="urn:schemas-microsoft-com:office:office"><KSOProductBuildVer dt:dt="string">2052-11.1.0.10700</KSOProductBuildVer><ICV dt:dt="string">320B9D8232AA4538B00E678D3BC23CE3</ICV></CustomDocumentProperties>
    <ExcelWorkbook xmlns="urn:schemas-microsoft-com:office:excel"><WindowWidth>20490</WindowWidth><WindowHeight>7860</WindowHeight><ProtectStructure>False</ProtectStructure><ProtectWindows>False</ProtectWindows></ExcelWorkbook>
    <Styles>
        <Style ss:ID="Default" ss:Name="Normal"><Alignment ss:Vertical="Center"/><Borders/><Font ss:FontName="宋体" x:CharSet="134" ss:Size="11" ss:Color="#000000"/><Interior/><NumberFormat/><Protection/></Style>
        <Style ss:ID="s49"><Alignment ss:Vertical="Center"/><Borders/><Font ss:FontName="宋体" x:CharSet="134" ss:Size="11" ss:Color="#000000"/><Interior/><NumberFormat/><Protection/></Style>
        <Style ss:ID="s50"><Alignment ss:Horizontal="Center" ss:Vertical="Center" ss:WrapText="1"/><Borders/><Font ss:FontName="方正黑体简体" x:CharSet="134" ss:Size="16" ss:Color="#000000" ss:Bold="1"/><Interior ss:Color="#FFFFFF" ss:Pattern="Solid"/></Style>
        <Style ss:ID="s51"><Alignment ss:Horizontal="Center" ss:Vertical="Center" ss:WrapText="1"/><Borders><Border ss:Position="Bottom" ss:LineStyle="Continuous" ss:Weight="1" ss:Color="#808080"/><Border ss:Position="Left" ss:LineStyle="Continuous" ss:Weight="1" ss:Color="#808080"/><Border ss:Position="Right" ss:LineStyle="Continuous" ss:Weight="1" ss:Color="#808080"/><Border ss:Position="Top" ss:LineStyle="Continuous" ss:Weight="1" ss:Color="#808080"/></Borders><Font ss:FontName="方正黑体简体" x:CharSet="134" ss:Size="12" ss:Color="#000000" ss:Bold="1"/><Interior ss:Color="#F79646" ss:Pattern="Solid"/></Style>
        <Style ss:ID="s52"><Alignment ss:Horizontal="Center" ss:Vertical="Center"/><Borders><Border ss:Position="Bottom" ss:LineStyle="Continuous" ss:Weight="1" ss:Color="#808080"/><Border ss:Position="Left" ss:LineStyle="Continuous" ss:Weight="1" ss:Color="#808080"/><Border ss:Position="Right" ss:LineStyle="Continuous" ss:Weight="1" ss:Color="#808080"/><Border ss:Position="Top" ss:LineStyle="Continuous" ss:Weight="1" ss:Color="#808080"/></Borders><Font ss:FontName="方正黑体简体" x:CharSet="134" ss:Size="12" ss:Color="#000000" ss:Bold="1"/><Interior ss:Color="#F79646" ss:Pattern="Solid"/></Style>
        <Style ss:ID="s53"><Alignment ss:Horizontal="Center" ss:Vertical="Center"/><Borders><Border ss:Position="Bottom" ss:LineStyle="Continuous" ss:Weight="1" ss:Color="#808080"/><Border ss:Position="Left" ss:LineStyle="Continuous" ss:Weight="1" ss:Color="#808080"/><Border ss:Position="Right" ss:LineStyle="Continuous" ss:Weight="1" ss:Color="#808080"/><Border ss:Position="Top" ss:LineStyle="Continuous" ss:Weight="1" ss:Color="#808080"/></Borders><Font ss:FontName="方正准圆简体" x:CharSet="134" ss:Size="12" ss:Color="#000000"/><Interior ss:Color="#DAEEF3" ss:Pattern="Solid"/></Style>
        <Style ss:ID="s54"><Alignment ss:Horizontal="Center" ss:Vertical="Center"/><Borders><Border ss:Position="Bottom" ss:LineStyle="Continuous" ss:Weight="1" ss:Color="#808080"/><Border ss:Position="Left" ss:LineStyle="Continuous" ss:Weight="1" ss:Color="#808080"/><Border ss:Position="Right" ss:LineStyle="Continuous" ss:Weight="1" ss:Color="#808080"/><Border ss:Position="Top" ss:LineStyle="Continuous" ss:Weight="1" ss:Color="#808080"/></Borders><Font ss:FontName="方正黑体简体" x:CharSet="134" ss:Size="12" ss:Color="#000000"/><Interior ss:Color="#DAEEF3" ss:Pattern="Solid"/></Style>
        <Style ss:ID="s55"><Alignment ss:Horizontal="Center" ss:Vertical="Center"/><Borders><Border ss:Position="Bottom" ss:LineStyle="Continuous" ss:Weight="1" ss:Color="#808080"/><Border ss:Position="Left" ss:LineStyle="Continuous" ss:Weight="1" ss:Color="#808080"/><Border ss:Position="Right" ss:LineStyle="Continuous" ss:Weight="1" ss:Color="#808080"/><Border ss:Position="Top" ss:LineStyle="Continuous" ss:Weight="1" ss:Color="#808080"/></Borders><Font ss:FontName="方正黑体简体" x:CharSet="134" ss:Size="12"/><Interior ss:Color="#DAEEF3" ss:Pattern="Solid"/></Style>
        <Style ss:ID="s56"><Alignment ss:Horizontal="Center" ss:Vertical="Center"/><Borders><Border ss:Position="Bottom" ss:LineStyle="Continuous" ss:Weight="1" ss:Color="#808080"/><Border ss:Position="Left" ss:LineStyle="Continuous" ss:Weight="1" ss:Color="#808080"/><Border ss:Position="Right" ss:LineStyle="Continuous" ss:Weight="1" ss:Color="#808080"/><Border ss:Position="Top" ss:LineStyle="Continuous" ss:Weight="1" ss:Color="#808080"/></Borders><Font ss:FontName="方正硬笔行书简体" x:CharSet="134" ss:Size="12" ss:Color="#000000"/><Interior ss:Color="#DAEEF3" ss:Pattern="Solid"/></Style>
        <Style ss:ID="s57"><Alignment ss:Horizontal="Center" ss:Vertical="Center"/><Borders><Border ss:Position="Bottom" ss:LineStyle="Continuous" ss:Weight="1" ss:Color="#808080"/><Border ss:Position="Left" ss:LineStyle="Continuous" ss:Weight="1" ss:Color="#808080"/><Border ss:Position="Right" ss:LineStyle="Continuous" ss:Weight="1" ss:Color="#808080"/><Border ss:Position="Top" ss:LineStyle="Continuous" ss:Weight="1" ss:Color="#808080"/></Borders><Font ss:FontName="方正准圆简体" x:CharSet="134" ss:Size="12" ss:Color="#000000"/><Interior ss:Color="#FFFFFF" ss:Pattern="Solid"/></Style>
        <Style ss:ID="s58"><Alignment ss:Horizontal="Center" ss:Vertical="Center"/><Borders><Border ss:Position="Bottom" ss:LineStyle="Continuous" ss:Weight="1" ss:Color="#808080"/><Border ss:Position="Left" ss:LineStyle="Continuous" ss:Weight="1" ss:Color="#808080"/><Border ss:Position="Right" ss:LineStyle="Continuous" ss:Weight="1" ss:Color="#808080"/><Border ss:Position="Top" ss:LineStyle="Continuous" ss:Weight="1" ss:Color="#808080"/></Borders><Font ss:FontName="方正黑体简体" x:CharSet="134" ss:Size="12" ss:Color="#000000"/><Interior ss:Color="#FFFFFF" ss:Pattern="Solid"/></Style>
        <Style ss:ID="s59"><Alignment ss:Horizontal="Center" ss:Vertical="Center"/><Borders><Border ss:Position="Bottom" ss:LineStyle="Continuous" ss:Weight="1" ss:Color="#808080"/><Border ss:Position="Left" ss:LineStyle="Continuous" ss:Weight="1" ss:Color="#808080"/><Border ss:Position="Right" ss:LineStyle="Continuous" ss:Weight="1" ss:Color="#808080"/><Border ss:Position="Top" ss:LineStyle="Continuous" ss:Weight="1" ss:Color="#808080"/></Borders><Font ss:FontName="方正黑体简体" x:CharSet="134" ss:Size="12" ss:Color="#FF0000"/><Interior ss:Color="#FFFFFF" ss:Pattern="Solid"/></Style>
        <Style ss:ID="s60"><Alignment ss:Horizontal="Center" ss:Vertical="Center"/><Borders><Border ss:Position="Bottom" ss:LineStyle="Continuous" ss:Weight="1" ss:Color="#808080"/><Border ss:Position="Left" ss:LineStyle="Continuous" ss:Weight="1" ss:Color="#808080"/><Border ss:Position="Right" ss:LineStyle="Continuous" ss:Weight="1" ss:Color="#808080"/><Border ss:Position="Top" ss:LineStyle="Continuous" ss:Weight="1" ss:Color="#808080"/></Borders><Font ss:FontName="方正准圆简体" x:CharSet="134" ss:Size="12" ss:Color="#000000"/><Interior/></Style>
        <Style ss:ID="s61"><Alignment ss:Horizontal="Center" ss:Vertical="Center"/><Borders><Border ss:Position="Bottom" ss:LineStyle="Continuous" ss:Weight="1" ss:Color="#808080"/><Border ss:Position="Left" ss:LineStyle="Continuous" ss:Weight="1" ss:Color="#808080"/><Border ss:Position="Right" ss:LineStyle="Continuous" ss:Weight="1" ss:Color="#808080"/><Border ss:Position="Top" ss:LineStyle="Continuous" ss:Weight="1" ss:Color="#808080"/></Borders><Font ss:FontName="方正硬笔行书简体" x:CharSet="134" ss:Size="12" ss:Color="#000000"/><Interior ss:Color="#FFFFFF" ss:Pattern="Solid"/></Style>
        <Style ss:ID="s62"><Alignment ss:Horizontal="Center" ss:Vertical="Center"/><Borders><Border ss:Position="Bottom" ss:LineStyle="Continuous" ss:Weight="1" ss:Color="#808080"/><Border ss:Position="Left" ss:LineStyle="Continuous" ss:Weight="1" ss:Color="#808080"/><Border ss:Position="Right" ss:LineStyle="Continuous" ss:Weight="1" ss:Color="#808080"/><Border ss:Position="Top" ss:LineStyle="Continuous" ss:Weight="1" ss:Color="#808080"/></Borders><Font ss:FontName="方正准圆简体" x:CharSet="134" ss:Size="13" ss:Color="#000000"/></Style>
        <Style ss:ID="s63"><Alignment ss:Horizontal="Left" ss:Vertical="Center"/><Borders><Border ss:Position="Bottom" ss:LineStyle="Continuous" ss:Weight="1" ss:Color="#808080"/><Border ss:Position="Left" ss:LineStyle="Continuous" ss:Weight="1" ss:Color="#808080"/><Border ss:Position="Right" ss:LineStyle="Continuous" ss:Weight="1" ss:Color="#808080"/><Border ss:Position="Top" ss:LineStyle="Continuous" ss:Weight="1" ss:Color="#808080"/></Borders><Font ss:FontName="方正准圆简体" x:CharSet="134" ss:Size="13"/></Style>
        <Style ss:ID="s64"><Alignment ss:Horizontal="Left" ss:Vertical="Center" ss:WrapText="1"/><Borders/><Font ss:FontName="方正黑体简体" x:CharSet="134" ss:Size="12"/><NumberFormat/></Style>
        <Style ss:ID="s65"><Alignment ss:Horizontal="Left" ss:Vertical="Center" ss:WrapText="1"/><Font ss:FontName="方正黑体简体" x:CharSet="134" ss:Size="12"/><NumberFormat/></Style>
        <Style ss:ID="s66"><Alignment ss:Horizontal="Left" ss:Vertical="Center" ss:WrapText="1"/><Font ss:FontName="方正黑体简体" x:CharSet="134" ss:Size="12" ss:Color="#595959"/><NumberFormat/></Style>
        <Style ss:ID="s67"><Alignment ss:Horizontal="Center" ss:Vertical="Center" ss:WrapText="1"/><Borders/><Font ss:FontName="方正黑体简体" x:CharSet="134" ss:Size="16" ss:Color="#000000" ss:Bold="1"/><Interior ss:Color="#FFFFFF" ss:Pattern="Solid"/></Style>
        <Style ss:ID="s68"><Alignment ss:Horizontal="Center" ss:Vertical="Center"/><Borders><Border ss:Position="Bottom" ss:LineStyle="Continuous" ss:Weight="1" ss:Color="#808080"/><Border ss:Position="Left" ss:LineStyle="Continuous" ss:Weight="1" ss:Color="#808080"/><Border ss:Position="Right" ss:LineStyle="Continuous" ss:Weight="1" ss:Color="#808080"/><Border ss:Position="Top" ss:LineStyle="Continuous" ss:Weight="1" ss:Color="#808080"/></Borders><Font ss:FontName="方正准圆简体" x:CharSet="134" ss:Size="13" ss:Color="#000000"/></Style>
        <Style ss:ID="s69"><Alignment ss:Horizontal="Left" ss:Vertical="Center"/><Borders><Border ss:Position="Bottom" ss:LineStyle="Continuous" ss:Weight="1" ss:Color="#808080"/><Border ss:Position="Left" ss:LineStyle="Continuous" ss:Weight="1" ss:Color="#808080"/><Border ss:Position="Right" ss:LineStyle="Continuous" ss:Weight="1" ss:Color="#808080"/><Border ss:Position="Top" ss:LineStyle="Continuous" ss:Weight="1" ss:Color="#808080"/></Borders><Font ss:FontName="方正准圆简体" x:CharSet="134" ss:Size="13"/></Style>
        <Style ss:ID="s70"><Alignment ss:Horizontal="Left" ss:Vertical="Center" ss:WrapText="1"/><Borders/><Font ss:FontName="方正黑体简体" x:CharSet="134" ss:Size="12"/><NumberFormat/></Style>
        <Style ss:ID="s71"><Alignment ss:Horizontal="Left" ss:Vertical="Center" ss:WrapText="1"/><Font ss:FontName="方正黑体简体" x:CharSet="134" ss:Size="12"/><NumberFormat/></Style>
    </Styles>
    <Worksheet ss:Name="计分表">
        <Table ss:ExpandedColumnCount="6" ss:ExpandedRowCount="7" x:FullColumns="1" x:FullRows="1" ss:DefaultColumnWidth="54" ss:DefaultRowHeight="13.5"><Column ss:Index="1" ss:StyleID="s49" ss:AutoFitWidth="0" ss:Width="39.75"/><Column ss:Index="2" ss:StyleID="s49" ss:AutoFitWidth="0" ss:Width="36.75"/><Column ss:StyleID="s49" ss:AutoFitWidth="0" ss:Width="115.5"/><Column ss:StyleID="s49" ss:AutoFitWidth="0" ss:Width="118.5"/><Column ss:StyleID="s49" ss:AutoFitWidth="0" ss:Width="156"/><Column ss:StyleID="s49" ss:AutoFitWidth="0" ss:Width="60.75"/><Row ss:Height="47.25"><Cell ss:StyleID="s67" ss:MergeAcross="5"><ss:Data ss:Type="String" xmlns="http://www.w3.org/TR/REC-html40"><B><Font html:Color="#000000"></Font><Font html:Color="#000000">小组赛计分表&#10;</Font></B><Font html:Size="12" html:Color="#000000">${groupingRule.playDate}</Font></ss:Data></Cell></Row>
            <Row ss:Height="30"><Cell ss:StyleID="s51"><Data ss:Type="String">顺序</Data></Cell><Cell ss:StyleID="s51"><Data ss:Type="String">队形</Data></Cell><Cell ss:StyleID="s52"><Data ss:Type="String">队伍一</Data></Cell><Cell ss:StyleID="s52"><Data ss:Type="String">队伍二</Data></Cell><Cell ss:StyleID="s52"><Data ss:Type="String">比分</Data></Cell><Cell ss:StyleID="s52"><Data ss:Type="String">裁判</Data></Cell></Row>
            <#list games as game>
                <#if (game_index+1) % 2 == 0>
                    <Row ss:Height="36"><Cell ss:StyleID="s53"><Data ss:Type="Number">${game_index+1}</Data></Cell><Cell ss:StyleID="s53"><Data ss:Type="String">${game.pkMode}</Data></Cell><Cell ss:StyleID="s54"><Data ss:Type="String">${game.firstTeamPlayer1} / ${game.firstTeamPlayer2}</Data></Cell><Cell ss:StyleID="s55"><Data ss:Type="String">${game.secondTeamPlayer1} / ${game.secondTeamPlayer2}</Data></Cell><Cell ss:StyleID="s53"><ss:Data ss:Type="String" xmlns="http://www.w3.org/TR/REC-html40"><Font html:Color="#000000"></Font><Font html:Color="#000000">${game.firstTeamName} </Font><U><Font html:Color="#000000">    </Font></U><Font html:Color="#000000"> : </Font><U><Font html:Color="#000000">    </Font></U><Font html:Color="#000000"> ${game.secondTeamName}</Font></ss:Data></Cell><Cell ss:StyleID="s56"><Data ss:Type="String">${game.judge}</Data></Cell></Row>
                <#else>
                    <Row ss:Height="39"><Cell ss:StyleID="s57"><Data ss:Type="Number">${game_index+1}</Data></Cell><Cell ss:StyleID="s57"><Data ss:Type="String">${game.pkMode}</Data></Cell><Cell ss:StyleID="s58"><ss:Data ss:Type="String" xmlns="http://www.w3.org/TR/REC-html40"><Font html:Color="#000000"></Font><Font html:Color="#000000">${game.firstTeamPlayer1} / </Font>${game.firstTeamPlayer2}</ss:Data></Cell><Cell ss:StyleID="s59"><ss:Data ss:Type="String" xmlns="http://www.w3.org/TR/REC-html40"><Font html:Color="#FF0000"></Font><Font html:Color="#FF0000"> </Font><Font html:Color="#000000">${game.secondTeamPlayer1} / ${game.secondTeamPlayer2}</Font></ss:Data></Cell><Cell ss:StyleID="s60"><ss:Data ss:Type="String" xmlns="http://www.w3.org/TR/REC-html40"><Font html:Color="#000000"></Font><Font html:Color="#000000">${game.firstTeamName} </Font><U><Font html:Color="#000000">    </Font></U><Font html:Color="#000000"> : </Font><U><Font html:Color="#000000">    </Font></U><Font html:Color="#000000"> ${game.secondTeamName}</Font></ss:Data></Cell><Cell ss:StyleID="s61"><Data ss:Type="String">${game.judge}</Data></Cell></Row>
                </#if>
            </#list>
            <Row ss:Height="33"><Cell ss:StyleID="s68" ss:MergeAcross="3"><ss:Data ss:Type="String" xmlns="http://www.w3.org/TR/REC-html40"><Font html:Color="#000000"></Font><Font html:Color="#000000">获胜组:</Font><Font html:Color="#000000">_______</Font></ss:Data></Cell><Cell ss:StyleID="s69" ss:MergeAcross="1"><ss:Data ss:Type="String" xmlns="http://www.w3.org/TR/REC-html40"><#list teams as team>${team.teamName}:___ </#list></ss:Data></Cell></Row>
            <Row ss:Height="38.25">
                <Cell ss:StyleID="s70" ss:MergeAcross="5">
                    <Data ss:Type="String"><#list teams as team>${team.teamName}: ${team.playersName}<#if team_has_next>&#10;</#if></#list></Data>
                </Cell>
            </Row>
            <Row ss:Height="41.25"><Cell ss:StyleID="s71" ss:MergeAcross="5"><Data ss:Type="String">分组赛共${groupingRule.games}局，每局21分制，${groupingRule.games}局累计总分高的一组为胜利组！</Data></Cell></Row>
        </Table>
        <WorksheetOptions xmlns="urn:schemas-microsoft-com:office:excel"><PageSetup><Header x:Margin="0.31496062992126"/><Footer x:Margin="0.31496062992126"/><PageMargins x:Left="0.708661417322835" x:Right="0.708661417322835" x:Top="0.196850393700787" x:Bottom="0.748031496062992"/></PageSetup><Selected/><TopRowVisible>0</TopRowVisible><LeftColumnVisible>0</LeftColumnVisible><PageBreakZoom>100</PageBreakZoom><Panes><Pane><Number>3</Number><ActiveRow>6</ActiveRow><ActiveCol>8</ActiveCol><RangeSelection>R7C9</RangeSelection></Pane></Panes><TabColorIndex>19</TabColorIndex><ProtectObjects>False</ProtectObjects><ProtectScenarios>False</ProtectScenarios></WorksheetOptions>
    </Worksheet>
</Workbook>
